In [1]:
import numpy as np
import tensorflow as tf

In [2]:
generated_mask=np.load('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/results/final Results all modility/results/complete results/results for combined with different ratios x_test real/8000 generated/masks.npy')
generated_mask.shape

(8000, 128, 128, 4)

In [3]:
generated_mri=np.load('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/results/final Results all modility/results/complete results/results for combined with different ratios x_test real/8000 generated/MRI.npy')
generated_mri.shape

(8000, 128, 128, 1)

In [4]:
np.unique(generated_mask), np.unique(generated_mri)

(array([0., 1.], dtype=float32),
 array([0.        , 0.05881732, 0.10863662, ..., 0.9999998 , 0.99999994,
        1.        ], dtype=float32))

In [5]:
import matplotlib.pyplot as plt


In [6]:
original_mri=np.load('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/data/appended all/training/appended flair/flair.npy')

In [7]:
original_masks=np.load('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/data/appended all/training/appended masks/masks.npy')

In [8]:
original_mri.shape,original_masks.shape

((195, 128, 128, 128), (195, 128, 128, 128))

In [9]:
image2D = []
mask2d=[]
for i in range(195):
  for j in range(128):
    image2D.append(original_mri[i,:,:,j])
    mask2d.append(original_masks[i,:,:,j])
original_mri = np.array(image2D)
original_masks=np.array(mask2d)
original_mri.shape,original_masks.shape

((24960, 128, 128), (24960, 128, 128))

In [10]:
original_mri=np.expand_dims(original_mri, axis = 3)
original_mri.shape

(24960, 128, 128, 1)

In [11]:
original_mri.shape,original_masks.shape,generated_mri.shape,generated_mask.shape

((24960, 128, 128, 1),
 (24960, 128, 128),
 (8000, 128, 128, 1),
 (8000, 128, 128, 4))

In [12]:
generated_mask=np.argmax(generated_mask,axis=3)
generated_mask.shape

(8000, 128, 128)

LETS seperate x_test and y_test from the real images

In [13]:
path_real=('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/results/final Results all modility/results/complete results/exp3 results for combined with different ratios x_test real/4:1/real xtest/')


In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(original_mri, original_masks, test_size = 0.10)

In [16]:
x_test.shape,x_train.shape,y_train.shape

((2496, 128, 128, 1), (22464, 128, 128, 1), (22464, 128, 128))

In [17]:
np.save(path_real+'x_test',x_test)
np.save(path_real+'y_test',y_test)

In [18]:
del x_train,x_test,y_train,y_test,

In [19]:
original_mri=original_mri[2496:,:,:]


In [20]:
original_mri.shape

(22464, 128, 128, 1)

In [21]:
original_masks=original_masks[2496:,:,:]
original_masks.shape

(22464, 128, 128)

In [22]:
original_mri.shape,original_masks.shape,generated_mask.shape,generated_mri.shape

((22464, 128, 128, 1),
 (22464, 128, 128),
 (8000, 128, 128),
 (8000, 128, 128, 1))

In [23]:
generated_mask=generated_mask[0:6000:,:,:]
generated_mask.shape

(6000, 128, 128)

In [24]:
generated_mri=generated_mri[0:6000:,:,:]
generated_mri.shape

(6000, 128, 128, 1)

In [ ]:
original_masks=tf.keras.utils.to_categorical(original_masks)
original_masks.shape

(22464, 128, 128, 4)

In [25]:
path_combined='/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/results/final Results all modility/results/complete results/exp3 results for combined with different ratios x_test real/4:1/combined/'

In [26]:
original_masks.shape,generated_mask.shape

((22464, 128, 128), (6000, 128, 128))

In [27]:
combined_mask=np.concatenate((original_masks, generated_mask))

In [28]:
combined_mask.shape

(28464, 128, 128)

In [29]:
np.save(path_combined+'combined_mask',combined_mask)

In [30]:
original_mri.shape,generated_mri.shape

((22464, 128, 128, 1), (6000, 128, 128, 1))

In [31]:
combined_mri=np.concatenate((original_mri, generated_mri))

In [32]:
combined_mri.shape

(28464, 128, 128, 1)

In [33]:
np.save(path_combined+'combined_mri',combined_mri)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [34]:
np.unique(combined_mask)

array([0, 1, 2, 3])

In [35]:
np.unique(combined_mri)

array([0.00000000e+00, 4.41111601e-04, 4.42282176e-04, ...,
       9.99999940e-01, 1.00000000e+00, 1.00000000e+00])

In [ ]:
np.min(combined_mri)

0.0