In [1]:
import numpy as np
import tensorflow as tf

In [2]:
generated_mask=np.load('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/results/final Results all modility/results/complete results/results for combined with different ratios x_test real/8000 generated/masks.npy')
generated_mask.shape

(8000, 128, 128, 4)

In [3]:
generated_mri=np.load('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/results/final Results all modility/results/complete results/results for combined with different ratios x_test real/8000 generated/MRI.npy')
generated_mri.shape

(8000, 128, 128, 1)

In [4]:
np.unique(generated_mask), np.unique(generated_mri)

(array([0., 1.], dtype=float32),
 array([0.        , 0.05881732, 0.10863662, ..., 0.9999998 , 0.99999994,
        1.        ], dtype=float32))

In [5]:
import matplotlib.pyplot as plt


In [6]:
original_mri=np.load('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/data/appended all/training/appended flair/flair.npy')

In [7]:
original_masks=np.load('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/data/appended all/training/appended masks/masks.npy')

In [8]:
original_mri.shape,original_masks.shape

((195, 128, 128, 128), (195, 128, 128, 128))

In [9]:
image2D = []
mask2d=[]
for i in range(195):
  for j in range(128):
    image2D.append(original_mri[i,:,:,j])
    mask2d.append(original_masks[i,:,:,j])
original_mri = np.array(image2D)
original_masks=np.array(mask2d)
original_mri.shape,original_masks.shape

((24960, 128, 128), (24960, 128, 128))

In [10]:
original_mri=np.expand_dims(original_mri, axis = 3)
original_mri.shape

(24960, 128, 128, 1)

In [11]:
original_mri.shape,original_masks.shape,generated_mri.shape,generated_mask.shape

((24960, 128, 128, 1),
 (24960, 128, 128),
 (8000, 128, 128, 1),
 (8000, 128, 128, 4))

In [ ]:
path_real=('/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/results/final Results all modility/results/complete results/exp 2 results for combined with different ratios x_test real/5:1/real /')


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(original_mri, original_masks, test_size = 0.10)

In [ ]:
x_test.shape,x_train.shape,y_train.shape

((2496, 128, 128, 1), (22464, 128, 128, 1), (22464, 128, 128))

In [ ]:
np.save(path_real+'x_test',x_test)
np.save(path_real+'y_test',y_test)

In [ ]:
y_test.shape,x_test.shape

((2496, 128, 128), (2496, 128, 128, 1))

In [ ]:
del x_train,x_test,y_train,y_test,

In [12]:
original_mri=original_mri[2496:,:,:]


In [13]:
original_masks=original_masks[2496:,:,:]
original_masks.shape

(22464, 128, 128)

In [14]:
generated_mask=generated_mask[0:4800:,:,:]
generated_mask.shape

(4800, 128, 128, 4)

In [15]:
np.unique(generated_mask)

array([0., 1.], dtype=float32)

In [16]:
np.unique(generated_mri)

array([0.        , 0.05881732, 0.10863662, ..., 0.9999998 , 0.99999994,
       1.        ], dtype=float32)

In [ ]:
generated_mask.shape

(4800, 128, 128, 4)

In [17]:
generated_mri=generated_mri[0:4800,:,:]
generated_mri.shape

(4800, 128, 128, 1)

In [18]:
path_combined='/content/drive/MyDrive/Brain_tumor_Segmentation/asad data/results/final Results all modility/results/complete results/exp3 results for combined with different ratios x_test real/5:1/combined/'

In [19]:
generated_mask=np.argmax(generated_mask,axis=3)

In [20]:
original_masks.shape,generated_mask.shape

((22464, 128, 128), (4800, 128, 128))

In [21]:
combined_mask=np.concatenate((original_masks, generated_mask))

In [22]:
combined_mask.shape

(27264, 128, 128)

In [23]:
np.save(path_combined+'combined_mask',combined_mask)

In [24]:
original_mri.shape,generated_mri.shape

((22464, 128, 128, 1), (4800, 128, 128, 1))

In [25]:
combined_mri=np.concatenate((original_mri, generated_mri))

In [26]:
np.save(path_combined+'combined_mri',combined_mri)